---
- name: restart azuracast
  ansible.builtin.command: >-
    docker compose -f {{ azuracast_base_dir }}/docker-compose.yml
    --project-directory {{ azuracast_base_dir }} restart
  args:
    chdir: "{{ azuracast_base_dir }}"
